# Generated by Django 5.2 on 2025-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_tag_promotion_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.AddField(
            model_name='promotion',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='ssubtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
