# Generated by Django 5.2 on 2025-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='promocoes/'),
        ),
    ]
